import { jsx as _jsx, jsxs as _jsxs } from "file:///Users/apple/Documents/ChatGPT/StarBox/.ui-verify/runtime/jsx-runtime.js";
import { Dialog as BaseDialog } from "file:///Users/apple/Documents/ChatGPT/StarBox/.ui-verify/runtime/base-ui.js";
import { RiCloseLine } from "file:///Users/apple/Documents/ChatGPT/StarBox/.ui-verify/runtime/remixicon.js";
import { Button } from "./button.js";
import { cn } from "../../lib/cn.js";
const DialogPrimitive = BaseDialog;
export function Modal({ open, title, description, onClose, children, className, }) {
    return (_jsx(DialogPrimitive.Root, { open: open, onOpenChange: (nextOpen) => { if (!nextOpen)
            onClose(); }, children: _jsxs(DialogPrimitive.Portal, { children: [_jsx(DialogPrimitive.Backdrop, { "data-slot": "dialog-backdrop", className: "fixed inset-0 z-50 bg-black/32 backdrop-blur-sm transition-opacity data-[ending-style]:opacity-0 data-[starting-style]:opacity-0" }), _jsx(DialogPrimitive.Viewport, { "data-slot": "dialog-viewport", className: "fixed inset-0 z-50 grid grid-rows-[1fr_auto_2fr] justify-items-center overflow-y-auto p-4 max-sm:grid-rows-[1fr_auto] max-sm:p-0 max-sm:pt-12", children: _jsxs(DialogPrimitive.Popup, { "data-slot": "dialog-popup", className: cn("relative row-start-2 flex max-h-[90vh] min-h-0 w-full max-w-lg flex-col overflow-hidden rounded-2xl border border-border bg-popover text-foreground shadow-2xl outline-none transition-[transform,opacity] data-[ending-style]:translate-y-2 data-[ending-style]:opacity-0 data-[starting-style]:translate-y-2 data-[starting-style]:opacity-0 max-sm:max-w-none max-sm:rounded-b-none", className), children: [_jsxs("div", { "data-slot": "dialog-header", className: "flex items-start justify-between gap-4 px-5 pb-3 pt-5", children: [_jsxs("div", { className: "min-w-0", children: [_jsx(DialogPrimitive.Title, { className: "text-base font-semibold", children: title }), description ? _jsx(DialogPrimitive.Description, { className: "mt-1 text-xs leading-5 text-muted-foreground", children: description }) : null] }), _jsx(DialogPrimitive.Close, { render: _jsx(Button, { variant: "ghost", size: "icon-sm", "aria-label": "\u5173\u95ED" }), children: _jsx(RiCloseLine, { className: "size-4", "aria-hidden": "true" }) })] }), _jsx("div", { "data-slot": "dialog-panel", className: "min-h-0 overflow-auto px-5 pb-5", children: children })] }) })] }) }));
}
