import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const source = (path) => readFileSync(path, "utf8");

test("Star cards keep a stable header rhythm and expose persisted AI analyzed state", () => {
  const card = source("src/features/repositories/repository-card.tsx");
  const page = source("src/features/repositories/repositories-page.tsx");

  assert.match(card, /className="flex h-5 w-full/);
  assert.match(card, /className="mt-0\.5 flex h-4 min-w-0 items-center gap-1\.5 overflow-hidden"/);
  assert.match(card, /text-\[11px\] leading-4 font-medium text-muted-foreground/);
  assert.doesNotMatch(card, /Badge variant="outline" size="sm" className="shrink-0 gap-1 rounded-md px-1\.5 text-xs"/);
  assert.doesNotMatch(card, /visibleStatusItems\.map/);
  assert.doesNotMatch(card, /hiddenStatusItems\.map/);
  assert.doesNotMatch(card, /key: "release"/);
  assert.doesNotMatch(card, /InfoIcon/);
  assert.match(card, /PencilIcon/);
  assert.doesNotMatch(card, /RiInformationLine|RiEditLine/);
  assert.match(card, /const aiAnalyzed = Boolean\(meta\.aiSummary\.trim\(\)\)/);
  assert.match(card, /AI 已分析，点击重新分析/);
  assert.match(card, /Tooltip content=\{t\("AI 已分析", "AI analyzed"\)\}/);
  assert.match(card, /SparklesIcon className="size-3\.5"/);
  assert.match(card, /import \{ BeamCard \} from "\.\.\/\.\.\/components\/spectrumui\/beam-card";/);
  assert.match(card, /<BeamCard active=\{aiLoading\} size="pulse-inner" colorVariant="colorful"[\s\S]*?<Card/);
  assert.match(card, /HoldToConfirmButton size="sm" iconOnly duration=\{1200\}/);
  assert.match(card, /holdingLabel=\{t\("继续按住以取消 Star", "Keep holding to unstar"\)\}/);
  assert.doesNotMatch(card, /Tooltip content=\{t\("按住取消 Star", "Hold to unstar"\)\}/);
  assert.match(card, /className="rounded-lg border-transparent bg-transparent text-muted-foreground hover:border-transparent hover:bg-destructive\/5 hover:text-destructive-foreground"/);
  const hold = source("src/components/spectrumui/hold-to-confirm.tsx");
  assert.match(hold, /holding && holdingLabel/);
  assert.match(hold, /bottom-full right-0 mb-1\.5 whitespace-nowrap/);
  assert.match(page, /onUnstar=\{\(\) => void unstar\(repo\)\}/);
  assert.doesNotMatch(page, /const \[unstarTarget/);
  assert.match(card, /data-repository-full-name=\{repository\.full_name\}/);
  assert.match(page, /querySelectorAll<HTMLElement>\("\[data-repository-full-name\]"\)/);
  assert.match(page, /scrollIntoView\(\{ behavior: reduceMotion \? "auto" : "smooth", block: "center", inline: "nearest" \}\)/);
  assert.match(page, /aiFollowPaused/);
  assert.match(page, /content-surface/);
  assert.match(page, /"wheel"/);
  assert.match(page, /"touchmove"/);
  assert.match(page, /继续跟随/);
  assert.match(page, /当前分析仓库不在筛选结果中；筛选条件保持不变/);
  assert.doesNotMatch(card, /ThinkingOrb/);
  assert.doesNotMatch(card, /role="status"/);
  assert.doesNotMatch(card, /opacity-65/);
  assert.doesNotMatch(card, /aiLoading && "animate-pulse/);
  assert.doesNotMatch(card, /\bdensity\b/);
  assert.doesNotMatch(page, /settings\.density|density=/);
});

test("repository AI keeps tags private and derives visible platforms from Releases", () => {
  const worker = source("worker/index.ts");
  const api = source("src/lib/api.ts");
  const types = source("src/types.ts");
  const page = source("src/features/repositories/repositories-page.tsx");
  const card = source("src/features/repositories/repository-card.tsx");
  const releaseAssets = source("src/lib/release-assets.ts");

  assert.match(worker, /tags \(2-5 short Chinese strings\)/);
  assert.match(worker, /const tags = Array\.isArray\(parsed\.tags\)/);
  assert.match(worker, /resolveReleasePlatforms\(request, env, fullName\)/);
  assert.match(worker, /releases\?per_page=5&page=1/);
  assert.match(worker, /Name: \$\{repo\.name\}/);
  assert.doesNotMatch(worker, /Stars: \$\{repo\.stargazers_count\}/);
  assert.doesNotMatch(worker, /Platform hints:/);
  assert.doesNotMatch(worker, /platforms \(array using only/);
  assert.match(api, /fullName: repository\.full_name/);
  assert.match(api, /name: repository\.name/);
  assert.doesNotMatch(api, /stargazers_count: repository\.stargazers_count/);
  assert.doesNotMatch(api, /owner: repository\.owner/);
  assert.match(types, /aiTags: string\[\]/);
  assert.match(types, /type AiOrganizeResult =[\s\S]*unchanged: true[\s\S]*summary: string;[\s\S]*category: string;[\s\S]*analysisMeta:/);
  assert.match(page, /\.\.\.meta\.aiTags/);
  assert.match(page, /aiTags: result\.tags/);
  assert.match(page, /inferReleasePlatforms/);
  assert.match(releaseAssets, /export function inferReleasePlatforms/);
  assert.doesNotMatch(card, /aria-label=\{t\("AI 标签", "AI tags"\)\}/);
  assert.doesNotMatch(card, /aiTags\.map/);
  assert.match(card, /aria-label=\{t\("根据 Release 附件与 GitHub Topics 识别的平台", "Platforms detected from Release assets and GitHub Topics"\)\}/);
  assert.doesNotMatch(card, /Release 平台/);
  assert.doesNotMatch(card, /AppleLogo|WindowsLogo|LinuxLogo|ShippingContainer/);
  assert.match(card, /根据 Release 附件与 GitHub Topics 识别，点击按平台筛选/);
  assert.match(card, /variant="outline" size="sm"/);
  assert.match(card, /const topics = Array\.from\(new Set\(repository\.topics\)\)/);
  assert.match(card, /relative mt-2\.5 h-5 min-w-0/);
  assert.match(card, /flex h-5 min-w-0 items-center gap-1 overflow-hidden/);
  assert.match(card, /ResizeObserver/);
  assert.match(card, /data-topic-measure/);
  assert.match(card, /hiddenTopics\.length/);
  assert.doesNotMatch(card, /topics\.slice\(/);
  assert.doesNotMatch(card, /hiddenTopicCount/);
  assert.match(card, /rounded-full bg-secondary\/25 px-1\.5 font-normal text-muted-foreground/);
  assert.doesNotMatch(card, /grid-cols-2/);
  assert.match(card, /暂无摘要或描述/);
  assert.match(card, /t\("备注", "Note"\)/);
  assert.match(card, /GitHub Topics；点击可筛选/);
  assert.doesNotMatch(card, /more Topics; view them in details/);
  assert.match(card, /onFilterTopic/);
  assert.match(card, /onFilterPlatform/);
  assert.match(page, /mergeRepositoryPlatforms/);
  assert.match(page, /"Docker"/);
});
test("page loading skeletons mirror their rendered layouts", () => {
  const skeleton = source("src/components/ui/skeleton.tsx");
  const discover = source("src/features/discover/discover-page.tsx");

  assert.match(skeleton, /variant = "star"/);
  assert.match(skeleton, /variant === "discover"/);
  assert.match(skeleton, /absolute right-4 top-4 z-10/);
  assert.match(skeleton, /mt-0\.5 flex h-4 min-w-0 items-center gap-1\.5 overflow-hidden/);
  assert.match(skeleton, /mt-2\.5 flex h-5 min-w-0 items-center gap-1 overflow-hidden/);
  assert.match(skeleton, /mt-2 flex min-w-0 items-center gap-1/);
  assert.match(skeleton, /mt-2 flex items-center justify-start gap-0\.5/);
  assert.match(skeleton, /grid-cols-\[minmax\(0,1fr\)_110px_140px_140px\]/);
  assert.match(skeleton, /max-md:grid-cols-\[minmax\(0,1fr\)_90px\]/);
  assert.match(skeleton, /grid gap-1 md:hidden/);
  assert.match(skeleton, /hidden md:block/);
  assert.match(discover, /grid gap-3 lg:grid-cols-2/);
  assert.match(discover, /RepositoryCardSkeleton key=\{index\} variant="discover"/);
  assert.doesNotMatch(discover, /RepositoryCardSkeleton key=\{index\} \/>/);
});
