import assert from "node:assert/strict";
import test from "node:test";
import { createExportPayload, createInitialState, loadState, mergeCanonicalServerState, mergeStarredRepositories, mergeSuccessfulReleaseFeed, normalizeState, saveState } from "../.test-build/client/lib/storage.js";

function storageStub() { const values = new Map(); return { getItem(key) { return values.has(key) ? values.get(key) : null; }, setItem(key, value) { values.set(key, String(value)); }, removeItem(key) { values.delete(key); }, clear() { values.clear(); } }; }

test("normalization keeps v5 UI defaults and active AI metadata while dropping retired settings and secrets", () => {
  const normalized = normalizeState({ version: 5, settings: { githubToken: "token", theme: "dark", density: "compact", navOrder: ["forks", "repositories"], ai: { providerName: "x", baseUrl: "https://api.example.com/v1", apiKey: "secret", model: "m", headers: {} } }, repositoryMeta: { "a/b": { category: "前端", note: "", aiSummary: "", aiTags: ["legacy"] } }, releaseSettings: { assetIncludePattern: "\\.zip$", assetExcludePattern: "checksum" } });
  assert.equal(normalized.version, 5); assert.equal(normalized.categories[0].name, "前端"); assert.equal(normalized.settings.githubToken, ""); assert.equal(normalized.settings.credentialConnected, false); assert.equal(normalized.settings.language, "zh-CN"); assert.deepEqual(normalized.notifications, []);
  assert.equal("navOrder" in normalized.settings, false); assert.equal("density" in normalized.settings, false); assert.deepEqual(normalized.repositoryMeta["a/b"].aiTags, ["legacy"]); assert.deepEqual(normalized.repositoryMeta["a/b"].aiPlatforms, []);
  for (const platform of ["macos", "windows", "linux"]) { assert.equal(normalized.releaseSettings.assetRules[platform].includePattern, "\\.zip$"); assert.equal(normalized.releaseSettings.assetRules[platform].excludePattern, "checksum"); }
});

test("UI snapshot temporarily keeps legacy AI secrets until encrypted cloud migration succeeds", () => {
  globalThis.localStorage = storageStub(); const state = createInitialState(); state.settings.githubToken = "github-secret"; state.settings.ai.apiKey = "ai-local-secret"; state.settings.ai.headers = { "X-Tenant": "team-a" }; state.settings.ai.credentialConfigured = false; saveState(state);
  const loaded = loadState(); const uiSnapshot = JSON.parse(globalThis.localStorage.getItem("starbox:ui:v5")); assert.equal(loaded.version, 5); assert.equal(uiSnapshot.settings.githubToken, ""); assert.equal(uiSnapshot.settings.ai.apiKey, "ai-local-secret"); assert.equal(uiSnapshot.settings.ai.headers["X-Tenant"], "team-a"); state.settings.ai.credentialConfigured = true; saveState(state); const migrated = JSON.parse(globalThis.localStorage.getItem("starbox:ui:v5")); assert.equal(migrated.settings.ai.apiKey, ""); assert.deepEqual(migrated.settings.ai.headers, {});
});

test("UI snapshot reload restores active preferences without retired settings fields", async () => {
  globalThis.localStorage = storageStub(); const state = createInitialState(); state.settings.githubToken = "runtime-github-token"; state.settings.theme = "dark"; state.settings.language = "en"; state.settings.accent = "blue"; state.settings.navOrder = ["forks", "repositories"]; state.settings.density = "compact"; state.settings.ai.providerName = "Local Provider"; state.settings.ai.apiKey = "local-api-key"; state.releaseSettings = { latestOnly: true, includePrereleases: false, assetRules: { macos: { includePattern: "\\.dmg$", excludePattern: "checksum" }, windows: { includePattern: "\\.exe$", excludePattern: "checksum" }, linux: { includePattern: "\\.AppImage$", excludePattern: "checksum" } }, pageSize: 50, syncPages: 5 }; saveState(state);
  const reloadedStorage = await import(`../.test-build/client/lib/storage.js?reload=${Date.now()}`); const reloaded = reloadedStorage.loadState(); const uiSnapshot = JSON.parse(globalThis.localStorage.getItem("starbox:ui:v5"));
  assert.equal(reloaded.settings.theme, "dark"); assert.equal(reloaded.settings.language, "en"); assert.equal(reloaded.settings.accent, "blue"); assert.equal(reloaded.settings.ai.providerName, "Local Provider"); assert.equal(reloaded.settings.ai.apiKey, "local-api-key"); assert.equal("navOrder" in reloaded.settings, false); assert.equal("density" in reloaded.settings, false); assert.equal("navOrder" in uiSnapshot.settings, false); assert.equal("density" in uiSnapshot.settings, false); assert.equal(reloaded.releaseSettings.syncPages, 5); assert.equal(reloaded.releaseSettings.pageSize, 50); assert.equal(reloaded.releaseSettings.assetRules.macos.includePattern, "\\.dmg$"); assert.equal(reloaded.releaseSettings.assetRules.windows.includePattern, "\\.exe$"); assert.equal(reloaded.releaseSettings.assetRules.linux.includePattern, "\\.AppImage$"); assert.equal("forkReadAt" in reloaded, false); assert.equal("releaseStates" in reloaded, false); assert.equal(uiSnapshot.settings.githubToken, "");
});

test("canonical server refresh replaces cloud business settings while preserving device-owned appearance", () => {
  const local = createInitialState(); local.settings.theme = "dark"; local.settings.language = "en"; local.settings.accent = "violet"; local.settings.ai = { providerName: "Local Provider", baseUrl: "https://local.example/v1", apiKey: "legacy-api-key", model: "local-model", headers: { "X-Tenant": "one" }, credentialConfigured: false }; local.releaseSettings.syncPages = 5; local.repositories = [{ full_name: "old/repo" }];
  const server = createInitialState(); server.repositories = [{ full_name: "canonical/repo" }]; server.settings.credentialConnected = true; server.settings.githubIdentity = { login: "octocat" }; server.settings.ai = { providerName: "Cloud AI", baseUrl: "https://ai.example/v1", apiKey: "", model: "cloud-model", headers: {}, credentialConfigured: true }; server.releaseSettings.syncPages = 3; server.releaseSettings.assetRules.macos.includePattern = "\\.dmg$"; server.releaseSettings.assetRules.windows.includePattern = "\\.msi$";
  const merged = mergeCanonicalServerState(local, server); assert.deepEqual(merged.repositories, server.repositories); assert.equal(merged.settings.credentialConnected, true); assert.equal(merged.settings.githubIdentity.login, "octocat"); assert.equal(merged.settings.theme, "dark"); assert.equal(merged.settings.language, "en"); assert.equal(merged.settings.accent, "violet"); assert.equal(merged.settings.ai.providerName, "Cloud AI"); assert.equal(merged.settings.ai.apiKey, ""); assert.deepEqual(merged.settings.ai.headers, {}); assert.equal(merged.settings.ai.credentialConfigured, true); assert.equal(merged.releaseSettings.syncPages, 3); assert.equal(merged.releaseSettings.assetRules.macos.includePattern, "\\.dmg$"); assert.equal(merged.releaseSettings.assetRules.windows.includePattern, "\\.msi$");
});

test("partial Stars response updates matching repositories and retains omitted local repositories", () => {
  const current = [{ full_name: "owner/refresh", stargazers_count: 10, description: "old description" }, { full_name: "owner/keep", stargazers_count: 5, description: "not in capped response" }]; const fetched = [{ full_name: "owner/refresh", stargazers_count: 15, description: "authoritative response" }, { full_name: "owner/new", stargazers_count: 1, description: "newly starred" }]; const merged = mergeStarredRepositories(current, fetched); assert.deepEqual(merged.map((repository) => repository.full_name), ["owner/refresh", "owner/keep", "owner/new"]); assert.equal(merged[0].stargazers_count, 15); assert.equal(merged[0].description, "authoritative response"); assert.equal(merged[1].description, "not in capped response");
});

test("failed Release pagination keeps partial pages and cursor staged until every required page succeeds", () => {
  const state = createInitialState(); state.releaseSubscriptions = ["owner/repo"]; state.lastReleaseSyncAt = "previous-sync"; const cachedRelease = { id: 100, repoFullName: "owner/repo", tagName: "v1", name: "v1", body: "", htmlUrl: "https://github.com/owner/repo/releases/tag/v1", publishedAt: "2026-09-01T00:00:00.000Z", createdAt: "2026-09-01T00:00:00.000Z", draft: false, prerelease: false, author: null, assets: [] }; state.releases = [cachedRelease]; const pageOneRelease = { id: 123, repoFullName: "owner/repo", tagName: "v2", name: "v2", body: "", htmlUrl: "https://github.com/owner/repo/releases/tag/v2", publishedAt: "2026-09-12T00:00:00.000Z", createdAt: "2026-09-12T00:00:00.000Z", draft: false, prerelease: false, author: null, assets: [] }; const staged = mergeSuccessfulReleaseFeed(state, [pageOneRelease], state.releaseSubscriptions, [{ fullName: "owner/repo", error: "page 2 returned 500" }], "new-sync"); assert.deepEqual(staged.releases, [cachedRelease]); assert.equal(staged.lastReleaseSyncAt, "previous-sync"); assert.equal(staged.releases[0].id, 100);
});

test("export payload strips GitHub and AI credentials while keeping safe headers", () => {
  const state = createInitialState(); state.settings.githubToken = "github-secret"; state.settings.ai.apiKey = "ai-secret"; state.settings.ai.headers = { Authorization: "secret", "X-Tenant": "safe" }; const payload = createExportPayload(state); assert.equal(payload.settings.githubToken, ""); assert.equal(payload.settings.credentialConnected, false); assert.equal(payload.settings.ai.apiKey, ""); assert.equal(payload.settings.ai.headers.Authorization, undefined); assert.equal(payload.settings.ai.headers["X-Tenant"], "safe");
});

test("entity cache schema omits obsolete read-state stores", async () => {
  const source = await import("node:fs").then(({ readFileSync }) => readFileSync("src/lib/storage.ts", "utf8")); for (const store of ["meta", "repositories", "repositoryMeta", "categories", "releaseSubscriptions", "releases", "forks", "notifications"]) assert.match(source, new RegExp(`\\"${store}\\"`)); assert.doesNotMatch(source, /releaseStates|forkReadAt|markForkReadState|CACHE_STORE|authoritative-state|createV4Backup|chunkMigrationPayload|checksumText/); assert.match(source, /fullName/); assert.match(source, /starredAt/); assert.match(source, /repoFullName\+publishedAt/); assert.match(source, /read\+createdAt/);
});

test("entity key paths match normalized bootstrap records", async () => {
  const source = await import("node:fs").then(({ readFileSync }) => readFileSync("src/lib/storage.ts", "utf8")); assert.match(source, /name === "repositories" \? "full_name"/); assert.match(source, /name === "repositoryMeta" \? "repositoryFullName"/); assert.match(source, /: "id"/); assert.match(source, /repositoryFullName, \.\.\.value/); assert.match(source, /releaseSubscriptions\.map\(\(repoFullName\) => \(\{ id: repoFullName, repoFullName \}\)\)/); assert.match(source, /forkJobs/);
});
