import {
  RiCheckLine,
  RiDatabase2Line,
  RiDownload2Line,
  RiFolder3Line,
  RiGitForkLine,
  RiGithubFill,
  RiKey2Line,
  RiPriceTag3Line,
  RiRefreshLine,
  RiSearchLine,
  RiSettings4Line,
  RiShieldCheckLine,
  RiStarLine,
  RiUpload2Line,
} from "@remixicon/react";
import { useEffect, useMemo, useRef, useState } from "react";
import type { ReactNode } from "react";
import { Alert, AlertDescription, AlertTitle } from "../../components/ui/alert";
import { AlertDialog, AlertDialogClose, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogPopup, AlertDialogTitle } from "../../components/ui/alert-dialog";
import { Button } from "../../components/ui/button";
import { Card } from "../../components/ui/card";
import { Checkbox } from "../../components/ui/checkbox";
import { Field } from "../../components/ui/field";
import { Input } from "../../components/ui/input";
import { Modal } from "../../components/ui/modal";
import { Select } from "../../components/ui/select";
import { FormSkeleton } from "../../components/ui/skeleton";
import { Tabs, TabsList, TabsPanel, TabsTab } from "../../components/ui/tabs";
import { Textarea } from "../../components/ui/textarea";
import { ToggleGroup, ToggleGroupItem } from "../../components/ui/toggle-group";
import { notify } from "../../components/ui/toast";
import { CategorySettingsPanel } from "../repositories/category-manager";
import { fetchGithubCredential, fetchGithubRateLimit, removeGithubCredential, replaceGithubCredential, testAiProvider, validateGithubToken } from "../../lib/api";
import { clearState, createInitialState, exportState, importState } from "../../lib/storage";
import { readQueryParam, replaceQueryParams } from "../../lib/url-state";
import type { AuthSession, GithubRateLimit, NavigationPageId, PersistedState } from "../../types";

type SettingsTab = "account" | "ai" | "categories" | "appearance" | "data";
const tabFromQuery = (): SettingsTab => { const value = readQueryParam("tab"); return value === "ai" || value === "categories" || value === "appearance" || value === "data" ? value : "account"; };
function SettingsBlock({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <Card className="grid gap-5 p-5 lg:grid-cols-[220px_minmax(0,1fr)]"><div><h2 className="text-sm font-semibold">{title}</h2><p className="mt-2 max-w-xs text-xs leading-5 text-muted-foreground">{description}</p></div><div className="grid min-w-0 gap-4">{children}</div></Card>; }
const navMeta: Record<NavigationPageId, { label: string; icon: typeof RiStarLine; required?: boolean }> = { repositories: { label: "Stars", icon: RiStarLine, required: true }, releases: { label: "Release", icon: RiPriceTag3Line }, forks: { label: "Fork", icon: RiGitForkLine }, lists: { label: "Lists", icon: RiFolder3Line }, discover: { label: "Discover", icon: RiSearchLine }, notifications: { label: "通知", icon: RiDatabase2Line }, settings: { label: "设置", icon: RiSettings4Line, required: true } };
function regexError(value: string) { if (!value.trim()) return ""; try { new RegExp(value, "i"); return ""; } catch (reason) { return reason instanceof Error ? reason.message : "正则无效"; } }

export function SettingsPage({ state, onStateChange, session, onLogout, onNavigatePath, initialLoading = false }: { state: PersistedState; onStateChange: (state: PersistedState) => void; session: AuthSession | null; onLogout: () => void; onNavigatePath: (path: string) => void; initialLoading?: boolean }) {
  const [tab, setTab] = useState<SettingsTab>(tabFromQuery);
  const [githubStatus, setGithubStatus] = useState("");
  const [githubTesting, setGithubTesting] = useState(false);
  const [rateLimits, setRateLimits] = useState<GithubRateLimit[]>([]);
  const [rateLoading, setRateLoading] = useState(false);
  const [aiStatus, setAiStatus] = useState("");
  const [aiTesting, setAiTesting] = useState(false);
  const [dataStatus, setDataStatus] = useState("");
  const [headersText, setHeadersText] = useState(() => JSON.stringify(state.settings.ai.headers, null, 2));
  const [headersError, setHeadersError] = useState("");
  const [credentialToken, setCredentialToken] = useState("");
  const [credentialStatus, setCredentialStatus] = useState("");
  const [credentialLoading, setCredentialLoading] = useState(false);
  const [removeCredentialOpen, setRemoveCredentialOpen] = useState(false);
  const [clearOpen, setClearOpen] = useState(false);
  const [importPreview, setImportPreview] = useState<PersistedState | null>(null);
  const [assetTestName, setAssetTestName] = useState("StarBox-1.0.0-macos-arm64.dmg");
  const fileRef = useRef<HTMLInputElement>(null);
  const settings = state.settings;
  const hasGithubCredential = Boolean(settings.githubToken.trim() || settings.credentialConnected);
  const returnTo = readQueryParam("returnTo");
  const includeError = regexError(state.releaseSettings.assetIncludePattern);
  const excludeError = regexError(state.releaseSettings.assetExcludePattern);
  const assetTest = useMemo(() => { if (includeError || excludeError) return "规则无效"; const included = !state.releaseSettings.assetIncludePattern || new RegExp(state.releaseSettings.assetIncludePattern, "i").test(assetTestName); const excluded = Boolean(state.releaseSettings.assetExcludePattern && new RegExp(state.releaseSettings.assetExcludePattern, "i").test(assetTestName)); return included && !excluded ? "会显示" : "会隐藏"; }, [assetTestName, state.releaseSettings.assetIncludePattern, state.releaseSettings.assetExcludePattern, includeError, excludeError]);
  useEffect(() => setHeadersText(JSON.stringify(settings.ai.headers, null, 2)), [settings.ai.headers]);
  useEffect(() => { replaceQueryParams({ tab: tab === "account" ? "" : tab }); }, [tab]);
  useEffect(() => { void fetchGithubCredential().then((credential) => onStateChange({ ...state, settings: { ...settings, githubIdentity: credential.identity ?? settings.githubIdentity, credentialConnected: credential.connected } })).catch(() => {}); }, []);

  function returnAfterCredential() { if (returnTo) onNavigatePath(returnTo); }
  async function replaceCredential() { const token = credentialToken.trim(); if (!token) return setCredentialStatus("请输入新的 GitHub Token"); setCredentialLoading(true); setCredentialStatus(""); try { const credential = await replaceGithubCredential(token); onStateChange({ ...state, settings: { ...settings, githubToken: token, githubIdentity: credential.identity, credentialConnected: credential.connected } }); setCredentialToken(""); setCredentialStatus(`已连接 @${credential.identity.login}；Token 不会在页面回显`); notify("GitHub 已连接", credential.identity.login, "success"); returnAfterCredential(); } catch (error) { try { const user = await validateGithubToken(token); onStateChange({ ...state, settings: { ...settings, githubToken: token, githubIdentity: { login: user.login, avatarUrl: user.avatarUrl }, credentialConnected: false } }); setCredentialToken(""); setCredentialStatus(`当前 Worker 使用兼容模式连接 @${user.login}`); returnAfterCredential(); } catch (fallbackError) { setCredentialStatus(fallbackError instanceof Error ? fallbackError.message : error instanceof Error ? error.message : "凭据连接失败"); } } finally { setCredentialLoading(false); } }
  async function removeCredential() { setRemoveCredentialOpen(false); setCredentialLoading(true); setCredentialStatus(""); try { await removeGithubCredential(); onStateChange({ ...state, settings: { ...settings, githubToken: "", githubIdentity: settings.githubIdentity, credentialConnected: false } }); setCredentialStatus("已移除加密 GitHub Token；GitHub identity binding 保留"); notify("GitHub Token 已移除", "身份绑定仍保留", "success"); } catch (error) { setCredentialStatus(error instanceof Error ? `${error.message}。请确认 Worker 已升级后重试。` : "移除凭据失败"); } finally { setCredentialLoading(false); } }
  async function testGithub() { if (!hasGithubCredential) return; setGithubTesting(true); setGithubStatus(""); try { const user = await validateGithubToken(settings.githubToken.trim()); setGithubStatus(`已连接 @${user.login}`); } catch (error) { setGithubStatus(error instanceof Error ? error.message : "连接失败"); } finally { setGithubTesting(false); } }
  async function loadRateLimits() { if (!hasGithubCredential) return; setRateLoading(true); try { setRateLimits((await fetchGithubRateLimit(settings.githubToken.trim())).resources); } catch (error) { setGithubStatus(error instanceof Error ? error.message : "Rate Limit 读取失败"); } finally { setRateLoading(false); } }
  function updateHeaders(raw: string) { setHeadersText(raw); try { const parsed = raw.trim() ? JSON.parse(raw) as unknown : {}; if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") throw new Error("Headers 必须是 JSON 对象"); const headers = Object.fromEntries(Object.entries(parsed).map(([key, value]) => [key, String(value)])); setHeadersError(""); onStateChange({ ...state, settings: { ...settings, ai: { ...settings.ai, headers } } }); } catch (reason) { setHeadersError(reason instanceof Error ? reason.message : "Headers JSON 无效"); } }
  async function testAi() { if (headersError) return setAiStatus(headersError); setAiTesting(true); setAiStatus(""); try { setAiStatus(await testAiProvider(settings.ai)); } catch (error) { setAiStatus(error instanceof Error ? error.message : "连接失败"); } finally { setAiTesting(false); } }
  function moveNav(index: number, delta: number) { const list = [...settings.navOrder]; const target = index + delta; if (target < 0 || target >= list.length) return; [list[index], list[target]] = [list[target], list[index]]; onStateChange({ ...state, settings: { ...settings, navOrder: list } }); }
  function toggleNav(id: NavigationPageId) { if (navMeta[id].required) return; const hidden = settings.hiddenNav.includes(id) ? settings.hiddenNav.filter((item) => item !== id) : [...settings.hiddenNav, id]; onStateChange({ ...state, settings: { ...settings, hiddenNav: hidden } }); }
  function updateReleaseSettings(patch: Partial<typeof state.releaseSettings>) { onStateChange({ ...state, releaseSettings: { ...state.releaseSettings, ...patch } }); }
  async function chooseImport(file: File) { try { setImportPreview(await importState(file)); setDataStatus(""); } catch (error) { setDataStatus(error instanceof Error ? error.message : "导入失败"); } }

  return <div className="mx-auto w-full max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
    <header className="mb-5"><h1 className="text-xl font-semibold tracking-tight">设置</h1><p className="mt-1 text-sm text-muted-foreground">账户与 GitHub、AI、分类、外观以及数据同步统一在这里管理。</p></header>
    {session?.defaultCredentialsActive ? <Alert variant="error" className="mb-5"><AlertTitle>Critical deployment warning</AlertTitle><AlertDescription>当前 Worker 正在使用默认登录凭据 admin / 000000，请立即配置生产账号与密码。</AlertDescription></Alert> : null}
    {initialLoading ? <FormSkeleton /> : <Tabs value={tab} onValueChange={(value: SettingsTab) => setTab(value)}>
      <TabsList className="mb-5 w-full justify-start overflow-x-auto rounded-none border-b border-border bg-transparent p-0"><TabsTab value="account">账户与 GitHub</TabsTab><TabsTab value="ai">AI</TabsTab><TabsTab value="categories">分类</TabsTab><TabsTab value="appearance">外观</TabsTab><TabsTab value="data">数据与同步</TabsTab></TabsList>
      <TabsPanel value="account" className="grid gap-4">
        <SettingsBlock title="登录会话" description="StarBox 登录由 Worker 会话保护；Cookie 不暴露给前端脚本。"><div className="flex flex-wrap items-center gap-3 rounded-xl bg-secondary/45 p-4"><RiShieldCheckLine className="size-5" /><div className="min-w-0 flex-1"><p className="text-sm font-medium">{session?.username || "已登录"}</p><p className="mt-1 text-xs text-muted-foreground">当前部署支持同一账号多设备会话。</p></div><Button variant="outline" onClick={onLogout}>退出登录</Button></div></SettingsBlock>
        <SettingsBlock title="GitHub 凭据" description="Token 由 Worker 管理并跨设备复用；Remove Token 只移除加密凭据，不解除 GitHub numeric identity binding。"><div className="rounded-xl bg-secondary/45 p-4"><p className="text-sm font-medium">{settings.githubIdentity ? `已绑定 @${settings.githubIdentity.login}` : "尚未绑定 GitHub"}</p><p className="mt-1 text-xs text-muted-foreground">{settings.credentialConnected ? "凭据由 Worker 管理，Token 不会返回浏览器。" : "身份绑定可以保留，即使 Token 已移除。"}</p></div><Field label="Connect / Replace Token"><Input type="password" autoComplete="off" value={credentialToken} placeholder="github_pat_…" onChange={(event) => setCredentialToken(event.target.value)} /></Field><div className="flex flex-wrap gap-2"><Button onClick={() => void replaceCredential()} loading={credentialLoading} disabled={!credentialToken.trim()}>连接 / 替换 Token</Button><Button variant="outline" onClick={() => setRemoveCredentialOpen(true)} disabled={!settings.githubToken && !settings.credentialConnected}>Remove Token</Button><Button variant="outline" onClick={() => void testGithub()} loading={githubTesting} disabled={!hasGithubCredential}>测试连接</Button><Button variant="outline" onClick={() => void loadRateLimits()} loading={rateLoading} disabled={!hasGithubCredential}><RiRefreshLine className="size-4" />API 配额</Button>{returnTo && hasGithubCredential ? <Button variant="ghost" onClick={returnAfterCredential}>返回原流程</Button> : null}</div>{credentialStatus || githubStatus ? <p className="text-xs text-muted-foreground">{credentialStatus || githubStatus}</p> : null}{rateLimits.length ? <div className="grid gap-2 sm:grid-cols-2">{rateLimits.map((item) => <div key={item.resource} className="rounded-lg border border-border p-3 text-xs"><div className="font-medium">{item.resource}</div><div className="mt-1 text-muted-foreground">{item.remaining.toLocaleString()} / {item.limit.toLocaleString()} remaining</div><div className="mt-1 text-muted-foreground">Reset {new Date(item.resetAt).toLocaleString("zh-CN")}</div></div>)}</div> : null}</SettingsBlock>
      </TabsPanel>
      <TabsPanel value="ai"><SettingsBlock title="AI Provider" description="仅使用自定义 HTTP Provider；配置自动保存在当前浏览器，本页不会把 API Key 同步到 D1。"><Field label="Provider 名称"><Input value={settings.ai.providerName} onChange={(event) => onStateChange({ ...state, settings: { ...settings, ai: { ...settings.ai, providerName: event.target.value } } })} /></Field><Field label="Base URL"><Input inputMode="url" value={settings.ai.baseUrl} onChange={(event) => onStateChange({ ...state, settings: { ...settings, ai: { ...settings.ai, baseUrl: event.target.value } } })} /></Field><Field label="Model"><Input value={settings.ai.model} onChange={(event) => onStateChange({ ...state, settings: { ...settings, ai: { ...settings.ai, model: event.target.value } } })} /></Field><Field label="API Key"><Input type="password" autoComplete="off" value={settings.ai.apiKey} onChange={(event) => onStateChange({ ...state, settings: { ...settings, ai: { ...settings.ai, apiKey: event.target.value } } })} /></Field><Field label="Headers JSON"><Textarea value={headersText} onChange={(event) => updateHeaders(event.target.value)} spellCheck={false} className="font-mono text-xs" />{headersError ? <span className="text-xs text-destructive-foreground">{headersError}</span> : <span className="text-xs text-muted-foreground">只会保存合法 JSON object；无效内容不会写入配置。</span>}</Field><div className="flex items-center gap-3"><Button variant="outline" onClick={() => void testAi()} loading={aiTesting} disabled={!settings.ai.baseUrl || !settings.ai.apiKey || !settings.ai.model || Boolean(headersError)}><RiKey2Line className="size-4" />测试 Provider</Button>{aiStatus ? <span className="text-xs text-muted-foreground">{aiStatus}</span> : null}</div></SettingsBlock></TabsPanel>
      <TabsPanel value="categories"><Card className="p-5"><div className="mb-5"><h2 className="text-sm font-semibold">分类管理</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">管理 Stars 的自定义分类；锁定分类不会被 AI 自动改写。</p></div><CategorySettingsPanel state={state} onStateChange={onStateChange} /></Card></TabsPanel>
      <TabsPanel value="appearance"><SettingsBlock title="外观与导航" description="主题、密度、强调色与主导航由前端即时应用。"><div className="grid gap-4 sm:grid-cols-3"><Field label="主题"><ToggleGroup value={[settings.theme]} onValueChange={(values) => { const value = values.at(-1); if (value === "system" || value === "light" || value === "dark") onStateChange({ ...state, settings: { ...settings, theme: value } }); }}><ToggleGroupItem value="system" className="w-auto px-3 text-xs">系统</ToggleGroupItem><ToggleGroupItem value="light" className="w-auto px-3 text-xs">浅色</ToggleGroupItem><ToggleGroupItem value="dark" className="w-auto px-3 text-xs">深色</ToggleGroupItem></ToggleGroup></Field><Field label="卡片密度"><ToggleGroup value={[settings.density]} onValueChange={(values) => { const value = values.at(-1); if (value === "comfortable" || value === "compact") onStateChange({ ...state, settings: { ...settings, density: value } }); }}><ToggleGroupItem value="comfortable" className="w-auto px-3 text-xs">舒适</ToggleGroupItem><ToggleGroupItem value="compact" className="w-auto px-3 text-xs">紧凑</ToggleGroupItem></ToggleGroup></Field><Field label="强调色"><Select value={settings.accent} onChange={(event) => onStateChange({ ...state, settings: { ...settings, accent: event.target.value as typeof settings.accent } })}><option value="neutral">中性</option><option value="blue">蓝色</option><option value="violet">紫色</option><option value="emerald">翠绿</option></Select></Field></div><div className="rounded-xl border border-border"><div className="border-b border-border px-3 py-2 text-xs font-semibold">导航顺序与显示</div>{settings.navOrder.map((id, index) => { const item = navMeta[id]; const Icon = item.icon; return <div key={id} className="flex items-center gap-2 border-b border-border px-3 py-2 last:border-b-0"><Icon className="size-4 text-muted-foreground" /><span className="flex-1 text-sm">{item.label}</span><label className="flex items-center gap-1.5 text-xs text-muted-foreground"><Checkbox checked={!settings.hiddenNav.includes(id)} disabled={item.required} onCheckedChange={() => toggleNav(id)} />显示</label><Button size="sm" variant="ghost" disabled={index === 0} onClick={() => moveNav(index, -1)}>上移</Button><Button size="sm" variant="ghost" disabled={index === settings.navOrder.length - 1} onClick={() => moveNav(index, 1)}>下移</Button></div>; })}</div></SettingsBlock></TabsPanel>
      <TabsPanel value="data" className="grid gap-4">
        <SettingsBlock title="Release 同步" description="Release 页面只消费 Stars 中的订阅；同步深度与 Asset Regex 集中在这里配置。"><div className="grid gap-4 md:grid-cols-2"><Field label="同步深度"><Select value={String(state.releaseSettings.syncPages)} onChange={(event) => updateReleaseSettings({ syncPages: Number(event.target.value) })}><option value="1">1 页 / 仓库</option><option value="3">3 页 / 仓库</option><option value="5">5 页 / 仓库</option></Select></Field><Field label="每页数量"><Select value={String(state.releaseSettings.pageSize)} onChange={(event) => updateReleaseSettings({ pageSize: Number(event.target.value) })}><option value="10">10</option><option value="20">20</option><option value="50">50</option></Select></Field><Field label="Asset include Regex"><Input value={state.releaseSettings.assetIncludePattern} onChange={(event) => updateReleaseSettings({ assetIncludePattern: event.target.value })} />{includeError ? <span className="text-xs text-destructive-foreground">{includeError}</span> : null}</Field><Field label="Asset exclude Regex"><Input value={state.releaseSettings.assetExcludePattern} onChange={(event) => updateReleaseSettings({ assetExcludePattern: event.target.value })} />{excludeError ? <span className="text-xs text-destructive-foreground">{excludeError}</span> : null}</Field></div><Field label="测试文件名"><Input value={assetTestName} onChange={(event) => setAssetTestName(event.target.value)} /><span className={`text-xs ${assetTest === "会显示" ? "text-success-foreground" : "text-muted-foreground"}`}>{assetTest}</span></Field></SettingsBlock>
        <SettingsBlock title="数据与缓存" description="D1 是权威数据源。导入必须先预览；清空只影响当前浏览器，不会删除 D1 云端数据。"><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => exportState(state)}><RiDownload2Line className="size-4" />导出 JSON</Button><Button variant="outline" onClick={() => fileRef.current?.click()}><RiUpload2Line className="size-4" />导入 JSON</Button><input ref={fileRef} type="file" accept="application/json" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; if (file) void chooseImport(file); event.currentTarget.value = ""; }} /><Button variant="destructive" onClick={() => setClearOpen(true)}>清空本地数据</Button></div><p className="text-xs leading-5 text-muted-foreground">导出文件会移除 GitHub Token、AI API Key 与敏感自定义 Headers。</p>{dataStatus ? <p className="flex items-center gap-1.5 text-xs text-muted-foreground"><RiCheckLine className="size-4" />{dataStatus}</p> : null}</SettingsBlock>
      </TabsPanel>
    </Tabs>}

    <AlertDialog open={removeCredentialOpen} onOpenChange={setRemoveCredentialOpen}><AlertDialogPopup><AlertDialogHeader><AlertDialogTitle>移除 GitHub Token？</AlertDialogTitle><AlertDialogDescription>只会删除 Worker 中保存的加密凭据。已绑定的 GitHub numeric identity 会继续保留，后续只能重新连接同一 GitHub 身份。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogClose render={<Button variant="ghost" />}>取消</AlertDialogClose><Button variant="destructive" onClick={() => void removeCredential()}>Remove Token</Button></AlertDialogFooter></AlertDialogPopup></AlertDialog>
    <AlertDialog open={clearOpen} onOpenChange={setClearOpen}><AlertDialogPopup><AlertDialogHeader><AlertDialogTitle>清空当前浏览器数据？</AlertDialogTitle><AlertDialogDescription>会清除 localStorage 与 IndexedDB 缓存，但不会删除 D1 云端数据。重新登录/同步后云端状态仍可恢复。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogClose render={<Button variant="ghost" />}>取消</AlertDialogClose><Button variant="destructive" onClick={() => { clearState(); onStateChange(createInitialState()); setClearOpen(false); setDataStatus("本地数据已清空；D1 未删除"); }}>清空本地数据</Button></AlertDialogFooter></AlertDialogPopup></AlertDialog>
    <Modal open={Boolean(importPreview)} title="导入预览" description="确认后才会替换当前浏览器状态。" onClose={() => setImportPreview(null)}>{importPreview ? <div className="grid gap-4"><div className="grid grid-cols-2 gap-2 text-sm"><div className="rounded-lg bg-secondary/50 p-3"><div className="text-xs text-muted-foreground">Repositories</div><div className="mt-1 font-semibold">{importPreview.repositories.length}</div></div><div className="rounded-lg bg-secondary/50 p-3"><div className="text-xs text-muted-foreground">Categories</div><div className="mt-1 font-semibold">{importPreview.categories.length}</div></div><div className="rounded-lg bg-secondary/50 p-3"><div className="text-xs text-muted-foreground">Release subscriptions</div><div className="mt-1 font-semibold">{importPreview.releaseSubscriptions.length}</div></div><div className="rounded-lg bg-secondary/50 p-3"><div className="text-xs text-muted-foreground">GitHub Lists</div><div className="mt-1 font-semibold">{importPreview.githubLists.length}</div></div></div><div className="flex justify-end gap-2"><Button variant="ghost" onClick={() => setImportPreview(null)}>取消</Button><Button onClick={() => { onStateChange(importPreview); setImportPreview(null); setDataStatus("导入成功"); notify("导入完成", "当前浏览器状态已替换", "success"); }}>确认导入</Button></div></div> : null}</Modal>
  </div>;
}
