import type { AccountRecord, D1Database, D1PreparedStatement, GithubCredentialRecord, SessionRecord } from "./types.js";

const nowIso = () => new Date().toISOString();
const encoded = (value: unknown) => JSON.stringify(value ?? {});
const decoded = (value: unknown) => { try { return typeof value === "string" ? JSON.parse(value) : value; } catch { return null; } };
const strings = (value: unknown) => Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];

type GithubListSnapshot = { id: string; name: string; description?: string | null; isPrivate?: boolean; items?: Array<{ id: string; fullName: string; htmlUrl?: string }> };

export class DataRepository {
  constructor(private readonly db: D1Database, private readonly clock: () => string = nowIso) {}
  private stmt(sql: string, ...values: unknown[]) { return this.db.prepare(sql).bind(...values); }
  async batch(statements: D1PreparedStatement[]) { const result: unknown[] = []; for (let i = 0; i < statements.length; i += 50) result.push(...await this.db.batch(statements.slice(i, i + 50))); return result; }

  async ensureAccount() { const now = this.clock(); await this.stmt("INSERT INTO app_account (account_id, created_at, updated_at) VALUES ('primary', ?1, ?1) ON CONFLICT(account_id) DO UPDATE SET updated_at = excluded.updated_at", now).run(); return (await this.account())!; }
  async account() { return this.stmt("SELECT account_id, github_user_id, github_login, revision, created_at, updated_at FROM app_account WHERE account_id = 'primary' LIMIT 1").first<AccountRecord>(); }
  async createSession(session: SessionRecord) { await this.stmt("INSERT INTO app_sessions (token_hash, account_id, created_at, expires_at, last_seen_at, revoked_at) VALUES (?1, 'primary', ?2, ?3, ?4, NULL)", session.token_hash, session.created_at, session.expires_at, session.last_seen_at).run(); }
  async sessionByHash(hash: string) { return this.stmt("SELECT token_hash, account_id, created_at, expires_at, last_seen_at, revoked_at FROM app_sessions WHERE token_hash = ?1 AND account_id = 'primary' LIMIT 1", hash).first<SessionRecord>(); }
  async touchSession(hash: string) { await this.stmt("UPDATE app_sessions SET last_seen_at = ?1 WHERE token_hash = ?2 AND account_id = 'primary' AND revoked_at IS NULL", this.clock(), hash).run(); }
  async revokeSession(hash: string) { await this.stmt("UPDATE app_sessions SET revoked_at = ?1 WHERE token_hash = ?2 AND account_id = 'primary'", this.clock(), hash).run(); }

  async credential() { return this.stmt("SELECT account_id, github_numeric_id, github_login, ciphertext, iv, key_version, fingerprint, validated_at, created_at, updated_at, status FROM github_credentials WHERE account_id = 'primary' LIMIT 1").first<GithubCredentialRecord>(); }
  async saveCredential(input: GithubCredentialRecord) { const now = this.clock(); await this.batch([this.stmt("INSERT INTO github_credentials (account_id, github_numeric_id, github_login, ciphertext, iv, key_version, fingerprint, validated_at, created_at, updated_at, status) VALUES ('primary', ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?8, ?9) ON CONFLICT(account_id) DO UPDATE SET github_numeric_id = excluded.github_numeric_id, github_login = excluded.github_login, ciphertext = excluded.ciphertext, iv = excluded.iv, key_version = excluded.key_version, fingerprint = excluded.fingerprint, validated_at = excluded.validated_at, updated_at = excluded.updated_at, status = excluded.status", input.github_numeric_id, input.github_login, input.ciphertext, input.iv, input.key_version, input.fingerprint, input.validated_at, now, input.status), this.stmt("UPDATE app_account SET github_user_id = ?1, github_login = ?2, updated_at = ?3 WHERE account_id = 'primary'", input.github_numeric_id, input.github_login, now)]); }
  async rotateCredential(input: Pick<GithubCredentialRecord, "ciphertext" | "iv" | "key_version" | "fingerprint">) { await this.stmt("UPDATE github_credentials SET ciphertext = ?1, iv = ?2, key_version = ?3, fingerprint = ?4, updated_at = ?5 WHERE account_id = 'primary'", input.ciphertext, input.iv, input.key_version, input.fingerprint, this.clock()).run(); }
  async deleteCredential() { await this.batch([this.stmt("DELETE FROM github_credentials WHERE account_id = 'primary'"), this.stmt("UPDATE app_account SET github_user_id = NULL, github_login = NULL, updated_at = ?1 WHERE account_id = 'primary'", this.clock())]); }

  async recordActivity(type: string, payload: unknown) { const id = crypto.randomUUID(); await this.stmt("INSERT INTO activity_log (id, account_id, type, payload_json, created_at) VALUES (?1, 'primary', ?2, ?3, ?4)", id, type, encoded(payload), this.clock()).run(); return id; }
  async listActivity(limit: number) { const rows = await this.stmt("SELECT id, type, payload_json, created_at FROM activity_log WHERE account_id = 'primary' ORDER BY created_at DESC LIMIT ?1", limit).all<{ id: string; type: string; payload_json: string; created_at: string }>(); return (rows.results ?? []).map(row => ({ ...row, payload: decoded(row.payload_json) })); }
  async listNotifications(limit: number) { const rows = await this.stmt("SELECT id, kind, title, body, read_at, created_at FROM notifications WHERE account_id = 'primary' ORDER BY created_at DESC LIMIT ?1", limit).all(); return rows.results ?? []; }
  async markNotificationRead(id: string) { await this.stmt("UPDATE notifications SET read_at = ?1 WHERE id = ?2 AND account_id = 'primary'", this.clock(), id).run(); }
  async addNotification(kind: string, title: string, body: string) { await this.stmt("INSERT INTO notifications (id, account_id, kind, title, body, read_at, created_at) VALUES (?1, 'primary', ?2, ?3, ?4, NULL, ?5)", crypto.randomUUID(), kind, title, body, this.clock()).run(); }

  async revision() { return (await this.stmt("SELECT revision FROM app_account WHERE account_id = 'primary' LIMIT 1").first<{ revision: number }>())?.revision ?? 0; }
  async change(entityType: string, entityKey: string, operation: string) { const revision = (await this.revision()) + 1; const now = this.clock(); await this.stmt("UPDATE app_account SET revision = ?1, updated_at = ?2 WHERE account_id = 'primary'", revision, now).run(); const row = await this.stmt("INSERT INTO sync_changes (account_id, entity_type, entity_key, operation, revision, created_at) VALUES ('primary', ?1, ?2, ?3, ?4, ?5) RETURNING seq", entityType, entityKey, operation, revision, now).first<{ seq: number }>(); return { seq: Number(row?.seq ?? 0), revision }; }
  async changes(after: number, limit: number) { const rows = await this.stmt("SELECT seq, account_id, entity_type, entity_key, operation, revision, created_at FROM sync_changes WHERE account_id = 'primary' AND seq > ?1 ORDER BY seq ASC LIMIT ?2", after, limit + 1).all(); const changes = rows.results ?? []; return { changes: changes.slice(0, limit), lastSeq: Number(changes.at(-1)?.seq ?? after), hasMore: changes.length > limit }; }

  async bootstrap() {
    const account = await this.account();
    const queries = [
      ["repositories", "SELECT * FROM repositories WHERE account_id = 'primary' AND is_starred = 1 ORDER BY updated_at DESC"],
      ["repositoryMeta", "SELECT * FROM repository_meta WHERE account_id = 'primary' ORDER BY updated_at DESC"],
      ["categories", "SELECT * FROM categories WHERE account_id = 'primary' ORDER BY sort_order, created_at"],
      ["releaseSubscriptions", "SELECT * FROM release_subscriptions WHERE account_id = 'primary'"],
      ["releases", "SELECT * FROM releases WHERE account_id = 'primary' ORDER BY COALESCE(published_at, created_at) DESC"],
      ["releaseStates", "SELECT * FROM release_states WHERE account_id = 'primary'"],
      ["forks", "SELECT * FROM forks WHERE account_id = 'primary' ORDER BY updated_at DESC"],
      ["githubLists", "SELECT * FROM github_lists WHERE account_id = 'primary' ORDER BY updated_at DESC"],
      ["githubListMemberships", "SELECT * FROM github_list_memberships WHERE account_id = 'primary' ORDER BY updated_at DESC"],
      ["notifications", "SELECT * FROM notifications WHERE account_id = 'primary' ORDER BY created_at DESC LIMIT 100"],
    ] as const;
    const entries = Object.fromEntries(await Promise.all(queries.map(async ([key, sql]) => [key, (await this.db.prepare(sql).all()).results ?? []] as const)));
    const memberships = (entries.githubListMemberships ?? []) as Array<Record<string, unknown>>;
    const githubLists = ((entries.githubLists ?? []) as Array<Record<string, unknown>>).map((list) => ({
      ...list,
      items: memberships.filter((membership) => membership.list_id === list.list_id).map((membership) => ({
        id: String(membership.github_repo_id ?? ""),
        fullName: String(membership.repo_full_name ?? ""),
        htmlUrl: String(membership.html_url ?? ""),
      })).filter((item) => item.fullName),
    }));
    delete (entries as Record<string, unknown>).githubListMemberships;
    entries.githubLists = githubLists;
    const credential = await this.credential();
    const lastSeq = await this.stmt("SELECT MAX(seq) AS seq FROM sync_changes WHERE account_id = 'primary'").first<{ seq: number }>();
    return { account, githubCredential: credential ? { connected: true, login: credential.github_login, githubUserId: credential.github_numeric_id, fingerprint: credential.fingerprint, keyVersion: credential.key_version } : { connected: false }, ...entries, revision: account?.revision ?? 0, lastSeq: Number(lastSeq?.seq ?? 0) };
  }

  async upsertRepository(repository: Record<string, unknown>, starred: boolean) { const now = this.clock(); const fullName = String(repository.full_name ?? ""); const repoId = String(repository.id ?? fullName); await this.stmt("INSERT INTO repositories (account_id, github_repo_id, full_name, name, html_url, description, language, default_branch, is_starred, starred_at, updated_at, raw_json) VALUES ('primary', ?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11) ON CONFLICT(account_id, github_repo_id) DO UPDATE SET full_name = excluded.full_name, name = excluded.name, html_url = excluded.html_url, description = excluded.description, language = excluded.language, default_branch = excluded.default_branch, is_starred = excluded.is_starred, starred_at = excluded.starred_at, updated_at = excluded.updated_at, raw_json = excluded.raw_json", repoId, fullName, String(repository.name ?? fullName.split("/").pop() ?? ""), String(repository.html_url ?? ""), typeof repository.description === "string" ? repository.description : null, typeof repository.language === "string" ? repository.language : null, String(repository.default_branch ?? "main"), starred ? 1 : 0, starred ? String(repository.starred_at ?? now) : null, now, encoded(repository)).run(); return this.change("repository", fullName, starred ? "upsert" : "tombstone"); }
  async listStarredFullNames() { const rows = await this.stmt("SELECT full_name FROM repositories WHERE account_id = 'primary' AND is_starred = 1").all<{ full_name: string }>(); return (rows.results ?? []).map((row) => row.full_name); }
  async markRepositoryUnstarred(fullName: string) { await this.stmt("UPDATE repositories SET is_starred = 0, starred_at = NULL, updated_at = ?1 WHERE account_id = 'primary' AND full_name = ?2", this.clock(), fullName).run(); return this.change("repository", fullName, "tombstone"); }

  async upsertRelease(release: Record<string, unknown>) { const repoFullName = String(release.repoFullName ?? ""); const releaseId = String(release.id ?? ""); const existing = await this.stmt("SELECT release_id FROM releases WHERE account_id = 'primary' AND release_id = ?1 LIMIT 1", releaseId).first<{ release_id: string }>(); await this.stmt("INSERT INTO releases (account_id, release_id, repo_full_name, tag_name, payload_json, published_at, created_at) VALUES ('primary', ?1, ?2, ?3, ?4, ?5, ?6) ON CONFLICT(account_id, release_id) DO UPDATE SET repo_full_name = excluded.repo_full_name, tag_name = excluded.tag_name, payload_json = excluded.payload_json, published_at = excluded.published_at", releaseId, repoFullName, String(release.tagName ?? ""), encoded(release), typeof release.publishedAt === "string" ? release.publishedAt : null, typeof release.createdAt === "string" ? release.createdAt : this.clock()).run(); const change = await this.change("release", releaseId, existing ? "update" : "upsert"); if (!existing) await this.addNotification("new_release", "发现新 Release", `${repoFullName} ${String(release.tagName ?? "")}`); await this.recordActivity("release_synced", { releaseId, repoFullName, newRelease: !existing }); return change; }
  async saveReleaseSyncState(repoFullName: string, cursor: string | null) { const revision = await this.revision(); const now = this.clock(); await this.stmt("INSERT INTO release_sync_state (account_id, repo_full_name, cursor, revision, last_synced_at, updated_at) VALUES ('primary', ?1, ?2, ?3, ?4, ?4) ON CONFLICT(account_id, repo_full_name) DO UPDATE SET cursor = excluded.cursor, revision = excluded.revision, last_synced_at = excluded.last_synced_at, updated_at = excluded.updated_at", repoFullName, cursor, revision, now).run(); }
  async subscribeRelease(repoFullName: string, subscribed: boolean) { if (subscribed) await this.stmt("INSERT INTO release_subscriptions (account_id, repo_full_name, created_at) VALUES ('primary', ?1, ?2) ON CONFLICT(account_id, repo_full_name) DO NOTHING", repoFullName, this.clock()).run(); else await this.stmt("DELETE FROM release_subscriptions WHERE account_id = 'primary' AND repo_full_name = ?1", repoFullName).run(); const change = await this.change("releaseSubscription", repoFullName, subscribed ? "upsert" : "tombstone"); await this.recordActivity(subscribed ? "release_subscribed" : "release_unsubscribed", { repoFullName }); return change; }
  async subscribeReleaseBatch(repoFullNames: string[]) { const unique = Array.from(new Set(repoFullNames.filter(Boolean))); for (const repoFullName of unique) await this.stmt("INSERT INTO release_subscriptions (account_id, repo_full_name, created_at) VALUES ('primary', ?1, ?2) ON CONFLICT(account_id, repo_full_name) DO NOTHING", repoFullName, this.clock()).run(); const change = await this.change("releaseSubscription", `batch:${crypto.randomUUID()}`, "batch_upsert"); await this.recordActivity("release_subscribed_batch", { count: unique.length, repoFullNames: unique }); return change; }
  async markReleaseRead(releaseId: string, readAt: string | null) { await this.stmt("INSERT INTO release_states (account_id, release_id, read_at) VALUES ('primary', ?1, ?2) ON CONFLICT(account_id, release_id) DO UPDATE SET read_at = excluded.read_at", releaseId, readAt).run(); const change = await this.change("releaseState", releaseId, readAt ? "upsert" : "tombstone"); await this.recordActivity(readAt ? "release_read" : "release_unread", { releaseId, readAt }); return change; }

  async saveFork(fullName: string, parentFullName: string | null, status: string, payload: unknown) {
    const now = this.clock();
    await this.stmt("INSERT INTO forks (account_id, full_name, parent_full_name, status, updated_at, payload_json) VALUES ('primary', ?1, ?2, ?3, ?4, ?5) ON CONFLICT(account_id, full_name) DO UPDATE SET parent_full_name = excluded.parent_full_name, status = excluded.status, updated_at = excluded.updated_at, payload_json = excluded.payload_json", fullName, parentFullName, status, now, encoded(payload)).run();
    const change = await this.change("fork", fullName, status === "deleted" ? "tombstone" : "upsert");
    await this.stmt("INSERT INTO fork_snapshots (account_id, repo_full_name, cursor, revision, status, created_at) VALUES ('primary', ?1, ?2, ?3, ?4, ?5)", fullName, null, change.revision, status, now).run();
    await this.stmt("INSERT INTO fork_events (id, account_id, repo_full_name, event_type, payload_json, created_at) VALUES (?1, 'primary', ?2, ?3, ?4, ?5)", crypto.randomUUID(), fullName, status.toUpperCase(), encoded(payload), now).run();
    await this.recordActivity(`fork_${status}`, { fullName, parentFullName }); if (status === "ready") await this.addNotification("fork_ready", "Fork 已就绪", fullName); if (status === "failed") await this.addNotification("fork_sync_failed", "Fork 操作失败", fullName); return change;
  }

  async saveList(list: { id: string; name: string; description?: string | null; isPrivate?: boolean }, operation = "upsert") { await this.stmt("INSERT INTO github_lists (account_id, list_id, name, description, is_private, updated_at) VALUES ('primary', ?1, ?2, ?3, ?4, ?5) ON CONFLICT(account_id, list_id) DO UPDATE SET name = excluded.name, description = excluded.description, is_private = excluded.is_private, updated_at = excluded.updated_at", list.id, list.name, list.description ?? null, list.isPrivate ? 1 : 0, this.clock()).run(); const change = await this.change("list", list.id, operation); await this.recordActivity(`list_${operation}`, { listId: list.id }); return change; }
  async deleteList(id: string) { await this.batch([this.stmt("DELETE FROM github_list_memberships WHERE account_id = 'primary' AND list_id = ?1", id), this.stmt("DELETE FROM github_lists WHERE account_id = 'primary' AND list_id = ?1", id)]); const change = await this.change("list", id, "tombstone"); await this.recordActivity("list_deleted", { listId: id }); return change; }
  async saveMembership(repoId: string, listIds: string[], repoFullName = "", htmlUrl = "") { await this.stmt("DELETE FROM github_list_memberships WHERE account_id = 'primary' AND github_repo_id = ?1", repoId).run(); for (const listId of listIds) await this.stmt("INSERT INTO github_list_memberships (account_id, list_id, github_repo_id, repo_full_name, html_url, updated_at) VALUES ('primary', ?1, ?2, ?3, ?4, ?5) ON CONFLICT(account_id, list_id, github_repo_id) DO UPDATE SET repo_full_name = excluded.repo_full_name, html_url = excluded.html_url, updated_at = excluded.updated_at", listId, repoId, repoFullName, htmlUrl, this.clock()).run(); const change = await this.change("listMembership", repoFullName || repoId, "upsert"); await this.recordActivity("list_membership_updated", { repoId, repoFullName, listIds }); return change; }
  async replaceListsSnapshot(lists: GithubListSnapshot[]) {
    await this.batch([this.stmt("DELETE FROM github_list_memberships WHERE account_id = 'primary'"), this.stmt("DELETE FROM github_lists WHERE account_id = 'primary'")]);
    for (const list of lists) {
      await this.stmt("INSERT INTO github_lists (account_id, list_id, name, description, is_private, updated_at) VALUES ('primary', ?1, ?2, ?3, ?4, ?5)", list.id, list.name, list.description ?? null, list.isPrivate ? 1 : 0, this.clock()).run();
      for (const item of list.items ?? []) await this.stmt("INSERT INTO github_list_memberships (account_id, list_id, github_repo_id, repo_full_name, html_url, updated_at) VALUES ('primary', ?1, ?2, ?3, ?4, ?5)", list.id, item.id, item.fullName, item.htmlUrl ?? `https://github.com/${item.fullName}`, this.clock()).run();
    }
    const change = await this.change("list", "snapshot", "replace"); await this.recordActivity("lists_synced", { count: lists.length }); return change;
  }

  private async upsertCategory(category: Record<string, unknown>) { const now = this.clock(); const id = String(category.id ?? category.categoryId ?? category.entityKey ?? ""); if (!id) throw new Error("Category ID 不能为空"); await this.stmt("INSERT INTO categories (account_id, category_id, name, color, sort_order, locked, created_at, updated_at) VALUES ('primary', ?1, ?2, ?3, ?4, ?5, ?6, ?6) ON CONFLICT(account_id, category_id) DO UPDATE SET name = excluded.name, color = excluded.color, sort_order = excluded.sort_order, locked = excluded.locked, updated_at = excluded.updated_at", id, String(category.name ?? "未分类"), typeof category.color === "string" ? category.color : null, Number(category.sortOrder ?? category.order ?? 0), category.locked ? 1 : 0, now).run(); return id; }
  private async upsertRepositoryMeta(fullName: string, payload: Record<string, unknown>) { const now = this.clock(); const aiTags = Array.isArray(payload.aiTags) ? payload.aiTags.map(String) : []; await this.stmt("INSERT INTO repository_meta (account_id, github_repo_id, category_id, note, pinned, ai_summary, ai_tags_json, updated_at) VALUES ('primary', ?1, ?2, ?3, ?4, ?5, ?6, ?7) ON CONFLICT(account_id, github_repo_id) DO UPDATE SET category_id = excluded.category_id, note = excluded.note, pinned = excluded.pinned, ai_summary = excluded.ai_summary, ai_tags_json = excluded.ai_tags_json, updated_at = excluded.updated_at", fullName, typeof payload.categoryId === "string" && payload.categoryId ? payload.categoryId : null, typeof payload.note === "string" ? payload.note : null, payload.pinned ? 1 : 0, typeof payload.aiSummary === "string" ? payload.aiSummary : null, encoded(aiTags), now).run(); }

  async mutate(operation: string, payload: Record<string, unknown>) {
    const now = this.clock();
    const entityType = typeof payload.entityType === "string" ? payload.entityType : operation.split(".")[0] || "state";
    const entityKey = typeof payload.entityKey === "string" ? payload.entityKey : typeof payload.fullName === "string" ? payload.fullName : typeof payload.id === "string" ? payload.id : crypto.randomUUID();
    if (operation === "release.subscribe" || operation === "release.unsubscribe") return this.subscribeRelease(String(payload.repoFullName ?? entityKey), operation === "release.subscribe");
    if (operation === "release.subscribe.batch") return this.subscribeReleaseBatch(strings(payload.repoFullNames));
    if (operation === "release.read" || operation === "release.unread") return this.markReleaseRead(String(payload.releaseId ?? entityKey), operation === "release.read" ? (typeof payload.readAt === "string" ? payload.readAt : now) : null);
    if (operation.startsWith("fork.")) return this.saveFork(entityKey, typeof payload.parentFullName === "string" ? payload.parentFullName : null, typeof payload.status === "string" ? payload.status : operation.split(".")[1] || "unknown", payload);
    if (operation === "list.delete") return this.deleteList(entityKey);
    if (operation === "list.membership") return this.saveMembership(String(payload.repoId ?? payload.fullName ?? entityKey), strings(payload.listIds), String(payload.repoFullName ?? payload.fullName ?? ""), typeof payload.htmlUrl === "string" ? payload.htmlUrl : "");
    if (operation === "list.create" || operation === "list.update") return this.saveList({ id: String(payload.listId ?? entityKey), name: String(payload.name ?? ""), description: typeof payload.description === "string" ? payload.description : null, isPrivate: Boolean(payload.isPrivate) }, operation === "list.create" ? "upsert" : "update");

    if (operation === "category.delete") { const id = String(payload.id ?? entityKey); await this.batch([this.stmt("UPDATE repository_meta SET category_id = NULL, updated_at = ?1 WHERE account_id = 'primary' AND category_id = ?2", now, id), this.stmt("DELETE FROM categories WHERE account_id = 'primary' AND category_id = ?1", id)]); await this.recordActivity("category_deleted", { id }); return this.change("category", id, "tombstone"); }
    if (operation === "category.reorder") { const categories = Array.isArray(payload.categories) ? payload.categories.map((item) => (item && typeof item === "object" ? item as Record<string, unknown> : {})) : []; for (const category of categories) await this.upsertCategory(category); await this.recordActivity("category_reordered", { count: categories.length }); return this.change("category", "order", "reorder"); }
    if (operation === "category.update" || operation === "category.create") { const id = await this.upsertCategory({ ...payload, id: payload.id ?? entityKey }); await this.recordActivity("category_updated", { id }); return this.change("category", id, "update"); }

    if (operation === "repository_meta.batch_category") { const names = strings(payload.repoFullNames); for (const fullName of names) { await this.stmt("INSERT INTO repository_meta (account_id, github_repo_id, category_id, note, pinned, ai_summary, ai_tags_json, updated_at) VALUES ('primary', ?1, ?2, NULL, 0, NULL, '[]', ?3) ON CONFLICT(account_id, github_repo_id) DO UPDATE SET category_id = excluded.category_id, updated_at = excluded.updated_at", fullName, typeof payload.categoryId === "string" && payload.categoryId ? payload.categoryId : null, now).run(); await this.change("repositoryMeta", fullName, "update"); } await this.recordActivity("repository_meta_batch_category", { count: names.length, categoryId: payload.categoryId ?? null }); return { seq: 0, revision: await this.revision() }; }
    if (operation === "repository_meta.ai" || operation === "repository_meta.update") { const category = payload.category && typeof payload.category === "object" ? payload.category as Record<string, unknown> : null; if (category) await this.upsertCategory(category); await this.upsertRepositoryMeta(entityKey, payload); await this.recordActivity(operation === "repository_meta.ai" ? "repository_ai_organized" : "repository_meta_updated", { fullName: entityKey }); return this.change("repositoryMeta", entityKey, "update"); }
    if (operation === "repository_meta.ai_batch") { const categories = Array.isArray(payload.categories) ? payload.categories : []; for (const item of categories) if (item && typeof item === "object") await this.upsertCategory(item as Record<string, unknown>); const items = Array.isArray(payload.items) ? payload.items : []; for (const item of items) if (item && typeof item === "object") { const record = item as Record<string, unknown>; const fullName = String(record.fullName ?? ""); if (!fullName) continue; await this.upsertRepositoryMeta(fullName, record); await this.change("repositoryMeta", fullName, "update"); } await this.recordActivity("repository_ai_organized_batch", { count: items.length }); return { seq: 0, revision: await this.revision() }; }

    await this.recordActivity(operation, payload);
    return this.change(entityType, entityKey, operation);
  }

  async saveSyncState(scope: string, cursor: string | null, revision: number) { await this.stmt("INSERT INTO sync_state (account_id, scope, cursor, revision, updated_at) VALUES ('primary', ?1, ?2, ?3, ?4) ON CONFLICT(account_id, scope) DO UPDATE SET cursor = excluded.cursor, revision = excluded.revision, updated_at = excluded.updated_at", scope, cursor, revision, this.clock()).run(); }
}
