import { useState } from "react";
import { AlertDialog, AlertDialogClose, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogPopup, AlertDialogTitle } from "../../components/ui/alert-dialog";
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";
import { Select } from "../../components/ui/select";
import { Switch } from "../../components/ui/switch";
import { Tooltip } from "../../components/ui/tooltip";
import { notify } from "../../components/ui/toast";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "../../components/ui/table";
import { runOptimisticMutation } from "../../lib/mutations";
import type { CategoryDefinition, PersistedState } from "../../types";

const colors = ["neutral", "blue", "violet", "emerald", "amber", "red"];
const colorClass: Record<string, string> = { neutral: "bg-muted-foreground", blue: "bg-blue-500", violet: "bg-violet-500", emerald: "bg-emerald-500", amber: "bg-amber-500", red: "bg-red-500" };

export function CategorySettingsPanel({ state, onStateChange }: { state: PersistedState; onStateChange: (state: PersistedState) => void }) {
  const [name, setName] = useState("");
  const [nameDrafts, setNameDrafts] = useState<Record<string, string>>({});
  const [error, setError] = useState("");
  const [deleteTarget, setDeleteTarget] = useState<CategoryDefinition | null>(null);

  async function commit(optimistic: PersistedState, operation: string, payload: Record<string, unknown>) {
    setError("");
    try { await runOptimisticMutation(state, optimistic, onStateChange, { operation, payload }); notify("分类已更新", "", "success"); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "分类保存失败"); }
  }
  function add() { const value = name.trim(); if (!value) return; if (state.categories.some((item) => item.name.trim().toLowerCase() === value.toLowerCase())) { setError("已存在同名分类"); return; } const category: CategoryDefinition = { id: `cat-${Date.now()}`, name: value, color: "neutral", order: state.categories.length, locked: false }; const categories = [...state.categories, category].map((item, index) => ({ ...item, order: index })); void commit({ ...state, categories }, "category.create", { id: category.id, name: category.name, color: category.color, sortOrder: category.order, locked: category.locked }); setName(""); }
  function update(category: CategoryDefinition, patch: Partial<CategoryDefinition>) { const nextName = patch.name?.trim() || category.name; const nextCategory = { ...category, ...patch, name: nextName }; const categories = state.categories.map((item) => item.id === category.id ? nextCategory : item).sort((a, b) => a.order - b.order); const repositoryMeta = nextName === category.name ? state.repositoryMeta : Object.fromEntries(Object.entries(state.repositoryMeta).map(([key, meta]) => [key, meta.category === category.name ? { ...meta, category: nextName } : meta])); void commit({ ...state, categories, repositoryMeta }, "category.update", { id: nextCategory.id, name: nextCategory.name, color: nextCategory.color, sortOrder: nextCategory.order, locked: nextCategory.locked }); }
  function commitName(category: CategoryDefinition) { const draft = nameDrafts[category.id]; if (draft === undefined) return; const nextName = draft.trim(); if (!nextName || nextName === category.name) { setNameDrafts((current) => { const next = { ...current }; delete next[category.id]; return next; }); return; } if (state.categories.some((item) => item.id !== category.id && item.name.trim().toLowerCase() === nextName.toLowerCase())) { setError("已存在同名分类"); return; } setNameDrafts((current) => { const next = { ...current }; delete next[category.id]; return next; }); update(category, { name: nextName }); }
  function move(index: number, delta: number) { const list = [...state.categories].sort((a, b) => a.order - b.order); const target = index + delta; if (target < 0 || target >= list.length) return; [list[index], list[target]] = [list[target], list[index]]; const categories = list.map((item, order) => ({ ...item, order })); void commit({ ...state, categories }, "category.reorder", { categories: categories.map((item) => ({ id: item.id, name: item.name, color: item.color, sortOrder: item.order, locked: item.locked })) }); }
  function remove(category: CategoryDefinition) { const repositoryMeta = Object.fromEntries(Object.entries(state.repositoryMeta).map(([key, meta]) => [key, meta.category === category.name ? { ...meta, category: "" } : meta])); const categories = state.categories.filter((item) => item.id !== category.id).map((item, order) => ({ ...item, order })); void commit({ ...state, categories, repositoryMeta }, "category.delete", { id: category.id }); setDeleteTarget(null); }
  const sorted = [...state.categories].sort((a, b) => a.order - b.order);

  return <div className="grid gap-5"><div className="flex flex-wrap gap-2"><Input className="max-w-sm" value={name} onChange={(event) => setName(event.target.value)} placeholder="新分类名称" onKeyDown={(event) => { if (event.key === "Enter") add(); }} /><Button onClick={add}>新建分类</Button></div>{error ? <p className="text-sm text-destructive-foreground" role="alert">{error}</p> : null}<Table variant="card"><TableHeader><TableRow><TableHead>名称</TableHead><TableHead className="w-36">颜色</TableHead><TableHead className="w-24">AI 锁定</TableHead><TableHead className="w-36">顺序</TableHead><TableHead className="w-24 text-right">操作</TableHead></TableRow></TableHeader><TableBody>{sorted.map((category, index) => <TableRow key={category.id}><TableCell><Input value={nameDrafts[category.id] ?? category.name} onChange={(event) => setNameDrafts((current) => ({ ...current, [category.id]: event.target.value }))} onBlur={() => commitName(category)} onKeyDown={(event) => { if (event.key === "Enter") { commitName(category); event.currentTarget.blur(); } else if (event.key === "Escape") { setNameDrafts((current) => { const next = { ...current }; delete next[category.id]; return next; }); event.currentTarget.blur(); } }} /></TableCell><TableCell><div className="flex items-center gap-2"><span className={`size-2.5 rounded-full ${colorClass[category.color] || colorClass.neutral}`} aria-hidden="true" /><Select value={category.color} onChange={(event) => update(category, { color: event.target.value })}>{colors.map((color) => <option key={color} value={color}>{color}</option>)}</Select></div></TableCell><TableCell><Tooltip content="锁定后 AI 整理不会自动改写该分类"><span><Switch checked={category.locked} onCheckedChange={(locked) => update(category, { locked })} aria-label={`锁定 ${category.name}`} /></span></Tooltip></TableCell><TableCell><div className="flex gap-1"><Button size="sm" variant="ghost" disabled={index === 0} onClick={() => move(index, -1)}>上移</Button><Button size="sm" variant="ghost" disabled={index === sorted.length - 1} onClick={() => move(index, 1)}>下移</Button></div></TableCell><TableCell className="text-right"><Button size="sm" variant="ghost" onClick={() => setDeleteTarget(category)}>删除</Button></TableCell></TableRow>)}</TableBody></Table>{!sorted.length ? <p className="py-6 text-center text-sm text-muted-foreground">还没有自定义分类</p> : null}<AlertDialog open={Boolean(deleteTarget)} onOpenChange={(open: boolean) => { if (!open) setDeleteTarget(null); }}><AlertDialogPopup><AlertDialogHeader><AlertDialogTitle>删除分类？</AlertDialogTitle><AlertDialogDescription>删除“{deleteTarget?.name}”后，使用该分类的仓库会变为未分类。此操作会同步到 D1。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogClose render={<Button variant="ghost" />}>取消</AlertDialogClose><Button variant="destructive" onClick={() => { if (deleteTarget) remove(deleteTarget); }}>删除</Button></AlertDialogFooter></AlertDialogPopup></AlertDialog></div>;
}
